//Filter
const DEFAULT_FILTER_MODE_SEARCH_WITH = 0;
const FILTER_MODE_ASCENDING = 1;
const FILTER_MODE_DESCENDING = 2;

//Menus
const DEFAULT_ACTIVE_MENU_ITEM_HOME = 0;
const DEFAULT_ACTIVE_MENU_ITEM_ABOUT = 1;
const DEFAULT_ACTIVE_MENU_ITEM_DETAIL_PAGE = 2;
const LEFT_MENU = 0;
const TOP_MENU = 1;

//Pagination
const DEFAULT_PAGE = 1;
const DEFAULT_PAGE_RANGE = 5;

// Event List
const SIZE_OF_PER_PAGE = 4;

//Searching
const DEFAULT_SEARCH_QUERY = "football";
export {
  DEFAULT_FILTER_MODE_SEARCH_WITH,
  SIZE_OF_PER_PAGE,
  LEFT_MENU,
  TOP_MENU,
  DEFAULT_ACTIVE_MENU_ITEM_HOME,
  DEFAULT_ACTIVE_MENU_ITEM_ABOUT,
  FILTER_MODE_ASCENDING,
  FILTER_MODE_DESCENDING,
  DEFAULT_PAGE,
  DEFAULT_PAGE_RANGE,
  DEFAULT_SEARCH_QUERY,
  DEFAULT_ACTIVE_MENU_ITEM_DETAIL_PAGE,
};
