const DEFAULT_FILTER_MODE_SEARCH_WITH = 0;
const LEFT_MENU = 0;
const TOP_MENU = 1;

const DEFAULT_ACTIVE_MENU_ITEM_HOME = 0;
const DEFAULT_ACTIVE_MENU_ITEM_ABOUT = 1;
export {
  DEFAULT_FILTER_MODE_SEARCH_WITH,
  LEFT_MENU,
  TOP_MENU,
  DEFAULT_ACTIVE_MENU_ITEM_HOME,
  DEFAULT_ACTIVE_MENU_ITEM_ABOUT,
};
